### ISSUE TITLE
HTML Issues in Documented Code Snippets

### ISSUE THREAD

**Issue by andrzej-casper** [CasperDash/useWallet#81]
I have encountered some HTML issues within the documented code snippets and wanted to bring them to your attention:

- Invalid `br` Tag:

  https://github.com/CasperDash/useWallet/blob/2ad8ca7cc24c53ce2a616e7ff630c204de4180cf/README.md?plain=1#L80
  
  Suggested fix: it should be written as `<br />`.

- Incorrectly Closed `button` Tag:

  https://github.com/CasperDash/useWallet/blob/2ad8ca7cc24c53ce2a616e7ff630c204de4180cf/packages/react/README.md?plain=1#L81
  
  Notice `utton` typo.
  
  https://github.com/CasperDash/useWallet/blob/2ad8ca7cc24c53ce2a616e7ff630c204de4180cf/docs/pages/react/hooks/useSign.mdx#L28
  
  https://github.com/CasperDash/useWallet/blob/2ad8ca7cc24c53ce2a616e7ff630c204de4180cf/docs/pages/react/hooks/useDisconnect.mdx#L24
  
  https://github.com/CasperDash/useWallet/blob/2ad8ca7cc24c53ce2a616e7ff630c204de4180cf/docs/pages/react/hooks/useSignMessage.mdx#L27
  
  Suggested fix: similar as in commit https://github.com/CasperDash/useWallet/commit/d91aa4051dddda76e8f25b221554953ed7140684.

Please ensure that the code samples are accurate and functioning as expected.

**Comment by hoailinh1210** [comment]
Thanks for your valuable feedback, I resolved it on tag https://github.com/CasperDash/useWallet/tree/docs-0.0.9.
If you do not have any concerns, I will close this ticket.
